#!/usr/bin/env python

import csv
from pathlib import Path
import sys

from more_itertools import windowed


for infile in sys.argv[1:]:
    outfile = Path(infile).with_suffix(".csv")
    with open(infile, "r") as f_in:
        lines = map(lambda x: x.rstrip(), f_in.readlines())
        noblanks = filter(lambda x: x, lines)
        windows = windowed(noblanks, 3)
    with open(outfile, "w") as f_out:
        poem_name = Path(infile).stem
        f_out.write(f"tags:poems poems::{poem_name}\n")
        writer = csv.writer(f_out, delimiter=';', lineterminator='\n')
        for window in windows:
            window = list(window)
            window[-1] = f"{{{{c1::{window[-1]}}}}}"
            writer.writerow(["<br>".join(window), ""])
